### ISSUE TITLE
Work on a way to show radio callsign instead

### ISSUE THREAD

**Issue by Kirollos** [Kirollos/DiscordEuroscope#1]
Example: Cairo Control instead of HECC_CTR

**Comment by Kirollos** [comment]
![image](https://user-images.githubusercontent.com/4985416/45322893-deccbd80-b549-11e8-8fb5-2cbe5a3e38ae.png)

There will be a file "DiscordEuroscope_RadioCallsigns.txt" (has to be beside the dll) that will contain a list of callsigns and their equivalent radio callsigns.

**Comment by Kirollos** [comment]
Added. https://github.com/Kirollos/DiscordEuroscope/releases/tag/v1.1.0

**Comment by Kirollos** [comment]
Added. [v1.1.0](https://github.com/Kirollos/DiscordEuroscope/releases/tag/v1.1.0)

**Comment by EoinAviation** [comment]
This can actually be extracted from the `CGroundToAirChannel` class, assuming the voice settings file is configured correctly. Removing the need for an extra file.

**Comment by Kirollos** [comment]
@EoinAviation Thanks for the suggestion, didn't pay attention to this class because it does not exist in the 3.1d API unfortunately. But I'll still try and look for alternatives other than that extra file.

**Comment by EoinAviation** [comment]
Ah, right you are!
I know there is a way to do it in 3.1d. Will create a pull request if i find out how ;)
