### ISSUE TITLE
PLUGINS ICON

### ISSUE THREAD

**Issue by theduc4a** [Kirollos/DiscordEuroscope#11]
Hello! Just ask if i can import my division icon into your plugins..... How can u do it?

**Comment by Kirollos** [comment]
Hello,
Create a new application from here https://discord.com/developers/applications where you can add your logos in it
then edit the application ID in here https://github.com/Kirollos/DiscordEuroscope/blob/master/DiscordEuroscope/DiscordEuroscopeExt.cpp#L10

You'll have to recompile.

**Comment by theduc4a** [comment]
Thanks, much appreciated!

**Comment by Kirollos** [comment]
Hi, you need Visual Studio.
1) Load the project using Visual Studio (2017 or newer)
2) Edit the application ID in the file mentioned in my previous reply
3) Make sure the build target is set to EuroScope 3.2 -> https://user-images.githubusercontent.com/4985416/50927860-b2766e80-1461-11e9-80d5-84598f30878b.png
4) Compile the plugin to obtain the new DLL.

**Comment by Kirollos** [comment]
I may consider in the near future to make this option configurable so you won't have to recompile manually.
