### ISSUE TITLE
Rich Presence icon doesn't show

### ISSUE THREAD

**Issue by MeshTheDev** [Kirollos/DiscordEuroscope#14]
After setting the application code and setting the images for the application, the rich presence icon does not show on my profile. Is there something im doing differently from your application? After replacing the application code with yours, the icon worked, I figure it probably is something that has to do with the application on my side.

**Comment by MeshTheDev** [comment]
edit: everything else works properly, just not the icon.

**Comment by MeshTheDev** [comment]
edit edit: i figured it out, the image name must be specified, and the icon must be added as a rich presence asset, and not the actual logo of the application/rich presence

file: DiscordEuroscopeExt.cpp : 

discordPresence.largeImageKey = "es";

change to

discordPresence.largeImageKey = "imagenamehere";

**Comment by Kirollos** [comment]
Hello, yes indeed, you have to add the icon as a rich presence asset & use its name in code. Furthermore, you can add more asset icons and modify the code to display different icons on different events (I've seen some forks doing that!).
