### ISSUE TITLE
Plugin doesn't show on Discord anymore

### ISSUE THREAD

**Issue by yasko1337** [Kirollos/DiscordEuroscope#15]
Hi there,

I have an issue with the Rich Presence not showing up on discord. I'm using ES version r34, do I have to downgrade in order to make it work?

**Comment by Kirollos** [comment]
It should work fine. Make sure that:
1. If you are running Discord as administrator, EuroScope must be launched as administrator as well.
2. Discord Activity Privacy is enabled.
