### ISSUE TITLE
Problem related to DiscordEuroscope_RadioCallsigns

### ISSUE THREAD

**Issue by ep3mhb** [Kirollos/DiscordEuroscope#2]
DiscordEuroscope_RadioCallsigns.txt updated with callsigns and positions i.e, "OIII_ APP Mehrabad Radar" but once loading the plugin and activating rich presence in Discord it is showing the callsign and frequency instead of position and frequency.

What shall I do?

The version of Euroscope is latest 3.2 beta 18

DiscordEuroscope version 1.1.0

**Comment by Kirollos** [comment]
Hi, if you hover with your mouse over the rich presence logo, radar callsign shows. Like in here:
https://user-images.githubusercontent.com/4985416/45330119-2b24f700-b564-11e8-81da-eba41a25583f.png

**Comment by ep3mhb** [comment]
Hello Mr. Kirollos,

Yes what you said is true at present. It is showing the callsign without
the need to feel the .txt file with callsign and position names.

Then the question is that what is the use of that .txt file?

I though the .txt file will convert the callsign to position names for
example if I login in with OIII_APP it will show in Discord Mehrabad Radar
if the .txt file contains below line:

OIII_APP Mehrabad Radar
OIII_TWR Mehrabad Tower
…

Please kindly clarify the use of .txt file if nothing can do with it.

Thanks

-- 
Mohammad H. Bahrololoum
Sent with Airmail

On October 22, 2018 at 6:32:24 PM, Kirollos (notifications@github.com)
wrote:

Hi, if you hover with your mouse over the rich presence logo, radar
callsign shows. Like in here:
https://user-images.githubusercontent.com/4985416/45330119-2b24f700-b564-11e8-81da-eba41a25583f.png

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kirollos/DiscordEuroscope/issues/2#issuecomment-431852876>,
or mute the thread

**Comment by Kirollos** [comment]
Dear Mr Mohammad,

> I though the .txt file will convert the callsign to position names for example if I login in with OIII_APP it will show in Discord Mehrabad Radar if the .txt file contains below line

This is true. It indeed doesn't replace the callsign (in the first line) with the radar callsign. It will only appear when you hover your mouse over this icon:
![](https://cdn.discordapp.com/app-assets/477907858072272896/489012366252441610.png)

It will show in a tooltip like in the screenshot I shared above ^.

**Comment by Kirollos** [comment]
Please let me know if you understood how it works.

**Comment by ep3mhb** [comment]
Dear Mr. Kirollos,

Good Night/Day,

Many thanks for your kind reply.

Yes, now I could see how it works.

-- 
Mohammad H. Bahrololoum
Sent with Airmail

On October 23, 2018 at 9:21:37 PM, Kirollos (notifications@github.com)
wrote:

Please let me know if you understood how it works.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Kirollos/DiscordEuroscope/issues/2#issuecomment-432339230>,
or mute the thread
