### ISSUE TITLE
Feature request: Add 3rd number after decimal to frequency

### ISSUE THREAD

**Issue by KuezyIT** [Kirollos/DiscordEuroscope#20]
Hello, after months of using the EuroScope Discord RPC, I came along something that is missing in the plugin.
The third number after the decimal is missing. Is there any reason why? If not, would it be possible to add the third number after the decimal into the Discord RPC?

Many thanks.

**Comment by Kirollos** [comment]
Hello, thanks for the report. It is supposed to do that. I'll mark this issue as a bug and I'll fix it.

**Comment by KuezyIT** [comment]
Thank you very much :D

**Comment by Kirollos** [comment]
Apparently, I've had it fixed already in this commit af2a4b6513c80a7782fb249ef48074f6a5cbe482, but I've never finished the version nor released it yet. Feel free to compile it from source and give it a try.
But anyway, I'll release a build before the end of September hopefully.

**Comment by Lucak1011** [comment]
Any update on this?

**Comment by Kirollos** [comment]
Hello @Lucak1011 ,
Please check the following:
https://github.com/Kirollos/DiscordEuroscope/discussions/23
https://forum.vatsim.net/t/euroscope-plugin-discordeuroscope-v1-3-0-progress-and-ideas/5346/13

https://github.com/Kirollos/DiscordEuroscope/releases

Looking forward to hear your thoughts and feedback.

Kirollos.

**Comment by Kirollos** [comment]
Fixed in https://github.com/Kirollos/DiscordEuroscope/commit/af2a4b6513c80a7782fb249ef48074f6a5cbe482

Will be released under 1.3.0
