### ISSUE TITLE
'Unresolved external symbol' error LNK2019

### ISSUE THREAD

**Issue by GeorgeBarlow** [Kirollos/DiscordEuroscope#4]
I keep getting this error when building. Could you give it a look and point me in the right direction , I am running VS 2017 with all the correct dependencies and done a clean clone of this project. 

https://paste.ee/p/90Lwl - Log file

Regards,
George

**Comment by Kirollos** [comment]
Hello,
I think it failed to find EuroScope's static library, before you compile, you know, there's build target, that originally has DEBUG or RELEASE in it. There are custom profiles called EuroScope31 and EuroScope32, I guess that's the issue.
Alternatively, if you don't want to bother yourself with compiling, you can just download the prebuilt .dll from the Releases pages!
Let me know how that goes :)

Best Regards,
Kirollos.

**Comment by Kirollos** [comment]
Like this:
![image](https://user-images.githubusercontent.com/4985416/50927860-b2766e80-1461-11e9-80d5-84598f30878b.png)

**Comment by GeorgeBarlow** [comment]
Worked like a charm! Thank you for that :)
