### ISSUE TITLE
Name Change 

### ISSUE THREAD

**Issue by elzarifb** [Kirollos/DiscordEuroscope#6]
Hello @Kirollos 

I have a simple request for a station name change. Is that done at your end or my end?

If your end, the station is OLBB_CTR as it is now Beirut Radar not Beirut Control.

**Comment by Kirollos** [comment]
Hi, this is done from your side. Modify DiscordEuroscope_RadioCallsigns.txt and redistribute it with your sectorfiles.

**Comment by elzarifb** [comment]
Thank you very much for your quick response. 

I will do that then. Really appreciate it.
