### ISSUE TITLE
Need help for its not working

### ISSUE THREAD

**Issue by LeoChen98** [Kirollos/DiscordEuroscope#7]
As the title, and I have set both ES and Discord launch as admin, but it doesn't work either.

What should I do to fix it?

system: windows 10 1909
ES version: 3.2a(r26)
Discord version: lastest by auto update.

**Comment by Kirollos** [comment]
Hi,
1- Does loading the plugin give any error?
2- If not, make sure game activity is enabled.

**Comment by LeoChen98** [comment]
> Hi,
> 1- Does loading the plugin give any error?
> 2- If not, make sure game activity is enabled.

Thanks for reply, but there is no error, and game activity is enabled, other games are able to display on discord but ES....

**Comment by seelenkrieger** [comment]
@Kirollos Same here
